In [1]:
!pip install numpy

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [6]:
#it's brief explanation,so don't worry if u can't understand, later on it's explained in detail 
import numpy as np #u can use any variable other than np also
a=np.array([1,2,3,4]) #it will be numpy array
print(a)
print(type(a))
a.shape #it's for dimension i.e (no. of rows, no.of columns)

[1 2 3 4]
<class 'numpy.ndarray'>


(4,)

In [7]:
#2-d numpy array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [10]:
#to take transpose of 2-d array b
c=b.T
c


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [13]:
#taking dot product of b matrix and c matrix
np.dot(b,c)

array([[ 30,  70],
       [ 70, 174]])

In [15]:
#creating a random array
np.random.randint(60,100,10) #range 60 to 100,marks of 10 students


array([94, 67, 66, 68, 89, 82, 93, 99, 91, 95])

In [17]:
#random 2-d array
matrix=np.random.randint(60,100,(5,5)) #range 60 to 100, (5,5)-rows and columns
print(matrix)

[[73 76 71 86 62]
 [73 75 86 69 95]
 [92 70 77 77 81]
 [83 62 71 82 84]
 [91 61 70 84 83]]


In [19]:
#to find largest/smallest element in matrix
x=np.max(matrix)
y=np.min(matrix)
print(x,y)

95 61


In [21]:
#to find minimum value's index number
a=np.array([0,1,3,-4,5,6,7])
b=np.argmin(a)
b

3

In [27]:
#to find unique numbers i.e repeating numbers will be present only once 
a=np.array([1,2,3,4,4,5,5,5,6,6,7])
b=np.unique(a,return_counts=True) #output will be sorted array 
print(b)            #return_count=True will give no. of occurrence of each element
print(b[0])
print(b[1])


(array([1, 2, 3, 4, 5, 6, 7]), array([1, 1, 1, 2, 3, 2, 1], dtype=int64))
[1 2 3 4 5 6 7]
[1 1 1 2 3 2 1]


In [29]:
#find number with highest frequency in array
a=np.array([1,2,3,4,4,5,5,5,6,6,7])
b=np.unique(a,return_counts=True)
index=np.argmax(b[1]) #index with highest frequency
print(index)
element=b[0][index]
print(element)


4
5


In [32]:
#slicing arrays
matrix=np.random.randint(60,100,(5,5)) #5*5 matrix with values from 60-100
print(matrix)
#slicing syntax [rows,columns] rows=start:end+1 columns=start:end+1
c=matrix[2:4,1:4] #from 2nd to 3th row, & 1st to 3th column
print(c)          #note-row and column counting starts from 0
                 

[[88 60 84 90 95]
 [89 68 95 90 90]
 [72 74 85 97 80]
 [87 71 62 96 88]
 [89 69 79 84 74]]
[[74 85 97]
 [71 62 96]]


In [3]:
#DATA VISUALIZATION
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'